# Nom de l'application
spring.application.name=kmerconnect-backend

# Base de données PostgreSQL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/kmerconnect}
spring.datasource.username=${DB_USER:kmerconnect_user}
spring.datasource.password=${DB_PASSWORD:local_password_dev}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth

# Serveur
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
