# Nom de l'application
spring.application.name=kmerconnect-backend

# Base de données PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_DB}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=auth

# Serveur
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
